/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author sport
 */
public class InfoRutaBuses extends javax.swing.JFrame {

    
    
    
    public InfoRutaBuses() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboNumBUS = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboID_Conductor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboOrigen = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboDestino = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jDateFechaPartida = new com.toedter.calendar.JDateChooser();
        jButtonAgregarRutaBus = new javax.swing.JButton();
        jButtonVolverRutaBuses = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboHora = new javax.swing.JComboBox<>();
        jComboMinutos = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInfoRuta = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar ruta de bus:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Elegir Numero de Bus:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 150, 40));

        getContentPane().add(jComboNumBUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Elegir conductor por ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        getContentPane().add(jComboID_Conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 163, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lugar de partida:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 110, 40));

        jComboOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barranquilla", "Malambo", "Palmar de Varela", "Sabanalarga", "Puerto Colombia", "Salgar", "Suan", "Campo de la Cruz", "Repelon", "Baranoa", "Galapa" }));
        getContentPane().add(jComboOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 160, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lugar de destino:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 30));

        jComboDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barranquilla", "Malambo", "Palmar de Varela", "Sabanalarga", "Puerto Colombia", "Salgar", "Suan", "Campo de la Cruz", "Repelon", "Baranoa", "Galapa" }));
        getContentPane().add(jComboDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha de partida:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 120, 30));
        getContentPane().add(jDateFechaPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 163, -1));

        jButtonAgregarRutaBus.setBackground(new java.awt.Color(204, 204, 255));
        jButtonAgregarRutaBus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAgregarRutaBus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarRutaBus.setText("Agregar ruta de bus");
        jButtonAgregarRutaBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarRutaBusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarRutaBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 173, 41));

        jButtonVolverRutaBuses.setBackground(new java.awt.Color(204, 204, 255));
        jButtonVolverRutaBuses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonVolverRutaBuses.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolverRutaBuses.setText("Volver");
        getContentPane().add(jButtonVolverRutaBuses, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 93, 41));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MM");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jComboHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        getContentPane().add(jComboHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 70, -1));

        jComboMinutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));
        getContentPane().add(jComboMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 70, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html><center>Información designada de la última ruta agregada:</center></html>");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 230, -1));

        jTextAreaInfoRuta.setEditable(false);
        jTextAreaInfoRuta.setColumns(20);
        jTextAreaInfoRuta.setRows(5);
        jTextAreaInfoRuta.setText("ID Ruta de bus\nNumero de bus\nPlaca de bus\nNombres y Apellidos de Conductor\nLugar de partida\nLugar de destino\nFecha de partida\nHora asignada de partida");
        jScrollPane1.setViewportView(jTextAreaInfoRuta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 290, 190));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hora de partida:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("HH");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3e11d0b4-01f7-4495-b1fc-1eea5bfc8a14.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarRutaBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarRutaBusActionPerformed

    }//GEN-LAST:event_jButtonAgregarRutaBusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoRutaBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoRutaBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoRutaBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoRutaBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoRutaBuses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAgregarRutaBus;
    public javax.swing.JButton jButtonVolverRutaBuses;
    public javax.swing.JComboBox<String> jComboDestino;
    public javax.swing.JComboBox<String> jComboHora;
    public javax.swing.JComboBox<String> jComboID_Conductor;
    public javax.swing.JComboBox<String> jComboMinutos;
    public javax.swing.JComboBox<String> jComboNumBUS;
    public javax.swing.JComboBox<String> jComboOrigen;
    public com.toedter.calendar.JDateChooser jDateFechaPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextAreaInfoRuta;
    // End of variables declaration//GEN-END:variables
}
