/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author sport
 */
public class InfoConductor extends javax.swing.JFrame {

    /**
     * Creates new form InfoConductor
     */
    public InfoConductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextConductor_id = new javax.swing.JTextField();
        jTextNombres_cond = new javax.swing.JTextField();
        jTextApellidos_cond = new javax.swing.JTextField();
        jButtonAnadirCond = new javax.swing.JButton();
        jComboBuscarID = new javax.swing.JComboBox<>();
        jButtonBuscarIDsConductor = new javax.swing.JButton();
        jButtonVerIDsEliminarConductor = new javax.swing.JButton();
        jTextModificarNombreConductor = new javax.swing.JTextField();
        jTextModificarApellidoConductor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboEliminarID = new javax.swing.JComboBox<>();
        jButtonEliminarConductor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInfoConductor = new javax.swing.JTable();
        jButtonActualizarTablaConductores = new javax.swing.JButton();
        jButtonHelpConductor = new javax.swing.JButton();
        jDateConductor = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jDateModificarConductor = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonVolverConductor = new javax.swing.JButton();
        jButtonModificarInfoConductor = new javax.swing.JButton();
        jButtonVerIDsModificarConductor = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jLabel16.setText("Buscar por Doc. Identidad:");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Doc Identidad" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombres");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html>Documento de Identidad</html>");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 60));
        getContentPane().add(jTextConductor_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 110, -1));

        jTextNombres_cond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombres_condActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNombres_cond, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 110, -1));
        getContentPane().add(jTextApellidos_cond, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 110, -1));

        jButtonAnadirCond.setBackground(new java.awt.Color(204, 204, 255));
        jButtonAnadirCond.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonAnadirCond.setText("Añadir");
        jButtonAnadirCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirCondActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnadirCond, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 100, 40));

        jComboBuscarID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Doc Identidad" }));
        jComboBuscarID.setEnabled(false);
        getContentPane().add(jComboBuscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 110, 110, -1));

        jButtonBuscarIDsConductor.setBackground(new java.awt.Color(204, 204, 255));
        jButtonBuscarIDsConductor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonBuscarIDsConductor.setText("Buscar");
        jButtonBuscarIDsConductor.setEnabled(false);
        getContentPane().add(jButtonBuscarIDsConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 120, 30));

        jButtonVerIDsEliminarConductor.setBackground(new java.awt.Color(204, 204, 255));
        jButtonVerIDsEliminarConductor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonVerIDsEliminarConductor.setText("Ver IDs");
        getContentPane().add(jButtonVerIDsEliminarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 90, 40));

        jTextModificarNombreConductor.setEnabled(false);
        getContentPane().add(jTextModificarNombreConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 120, -1));

        jTextModificarApellidoConductor.setEnabled(false);
        getContentPane().add(jTextModificarApellidoConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 120, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombres");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Apellidos");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Eliminar conductor:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Buscar por Doc. Identidad:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        jComboEliminarID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Doc Identidad" }));
        jComboEliminarID.setEnabled(false);
        getContentPane().add(jComboEliminarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 160, -1));

        jButtonEliminarConductor.setBackground(new java.awt.Color(204, 204, 255));
        jButtonEliminarConductor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonEliminarConductor.setText("Eliminar");
        jButtonEliminarConductor.setEnabled(false);
        getContentPane().add(jButtonEliminarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 110, 40));

        jTableInfoConductor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Fecha Nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableInfoConductor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 668, 94));

        jButtonActualizarTablaConductores.setBackground(new java.awt.Color(204, 204, 255));
        jButtonActualizarTablaConductores.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonActualizarTablaConductores.setText("Actualizar tabla");
        getContentPane().add(jButtonActualizarTablaConductores, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 150, 40));

        jButtonHelpConductor.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHelpConductor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonHelpConductor.setText("Ayuda");
        jButtonHelpConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpConductorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHelpConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 100, 40));

        jDateConductor.setDateFormatString("yyyy-MM-d");
        getContentPane().add(jDateConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html>Fecha de nacimiento</html>");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, 60));

        jDateModificarConductor.setEnabled(false);
        getContentPane().add(jDateModificarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 120, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("<html>Fecha de nacimiento</html>");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 90, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Añadir conductor:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html><center>Modificar información de un conductor:</center></html>");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 280, 90));

        jButtonVolverConductor.setBackground(new java.awt.Color(204, 204, 255));
        jButtonVolverConductor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonVolverConductor.setText("Volver");
        getContentPane().add(jButtonVolverConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 100, 40));

        jButtonModificarInfoConductor.setBackground(new java.awt.Color(204, 204, 255));
        jButtonModificarInfoConductor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonModificarInfoConductor.setText("Modificar información");
        jButtonModificarInfoConductor.setEnabled(false);
        getContentPane().add(jButtonModificarInfoConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 160, 40));

        jButtonVerIDsModificarConductor.setBackground(new java.awt.Color(204, 204, 255));
        jButtonVerIDsModificarConductor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonVerIDsModificarConductor.setText("Ver IDs");
        getContentPane().add(jButtonVerIDsModificarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 90, 40));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Captura2.PNG"))); // NOI18N
        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 120, 120));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3e11d0b4-01f7-4495-b1fc-1eea5bfc8a14.jpg"))); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 860, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnadirCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirCondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnadirCondActionPerformed

    private void jTextNombres_condActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombres_condActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombres_condActionPerformed

    private void jButtonHelpConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHelpConductorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoConductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonActualizarTablaConductores;
    public javax.swing.JButton jButtonAnadirCond;
    public javax.swing.JButton jButtonBuscarIDsConductor;
    public javax.swing.JButton jButtonEliminarConductor;
    public javax.swing.JButton jButtonHelpConductor;
    public javax.swing.JButton jButtonModificarInfoConductor;
    public javax.swing.JButton jButtonVerIDsEliminarConductor;
    public javax.swing.JButton jButtonVerIDsModificarConductor;
    public javax.swing.JButton jButtonVolverConductor;
    private javax.swing.JComboBox<String> jComboBox8;
    public javax.swing.JComboBox<String> jComboBuscarID;
    public javax.swing.JComboBox<String> jComboEliminarID;
    public com.toedter.calendar.JDateChooser jDateConductor;
    public com.toedter.calendar.JDateChooser jDateModificarConductor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableInfoConductor;
    public javax.swing.JTextField jTextApellidos_cond;
    public javax.swing.JTextField jTextConductor_id;
    public javax.swing.JTextField jTextModificarApellidoConductor;
    public javax.swing.JTextField jTextModificarNombreConductor;
    public javax.swing.JTextField jTextNombres_cond;
    // End of variables declaration//GEN-END:variables
}
